version: 0.2

phases:
  install:
      commands:
         - echo comando de instalacion ...
         - javac -version
         - gradle --status
  build:
       commands:
         - echo Ensamblando arrancando `date`
         - echo Compilando un codigo...
         - gradle -s --no-daemon --console plain build
        
  post_build:
       commands:
         - echo Ensamblando completado `date`
         - ls -R ./build/libs
         - echo Imagen docker creada
artifacts:
  files:
    -  build/libs/sd-credit-management-v2-0.0.1-SNAPSHOT.jar