apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.creditmgm.name}}
  labels:
    app: {{.Values.creditmgm.name}}
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{.Values.creditmgm.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.creditmgm.name}}
    spec:
      containers:
      - image: {{ .Values.creditmgm.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: {{.Values.creditmgm.name}}
        ports:
        - containerPort: 3000
          protocol: TCP
