# Default values for eksdemo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Release-wide Values
replicas: 1
version: 'latest'

# Service Specific Values
creditmgm:
  name: sd-credit-management
  image: 456220669037.dkr.ecr.us-east-1.amazonaws.com/sdcreditmanagement
